version: '3.8'

services:
  server:
    image: local/jarvis/server-base:1
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stop_grace_period: 1s
    build:
      context: ../server
      dockerfile: "${PWD}/Dockerfile-server-base"
    volumes:
      - "${PWD}/..:/app"
      - "${PWD}/volumes/root-.cache:/root/.cache"
    working_dir: /app/server
    # entrypoint: python
    # command: [ "awesome_chat.py",  "--config" , "config.yaml",  "--mode",  "server"]
    entrypoint: sleep
    command: infinity
    ports:
      - 8004:8004
      - 8005:8005


  # hgpt:
  #   image: registry.hf.space/microsoft-hugginggpt:latest
  #   platform: linux/amd64
  #   entrypoint: python
  #   command: app.py
  #   ports:
  #     - 7860:7860

  webclient:
    image: local/jarvis/web-client:1
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stop_grace_period: 1s
    build:
      context: ../web
      dockerfile: "${PWD}/Dockerfile-webclient-base"
    volumes:
      - "${PWD}/..:/app"
    working_dir: /app/web
    # entrypoint: npm
    # command: [ "run",  "dev"]
    entrypoint: sleep
    command: infinity
    ports:
      - 9999:9999
